name: brush step

on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ main ]
  schedule:
    - cron: '35 0,3,5,9,12,14 * * *'
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests pytz pycryptodome
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          open_get_weather='${{ secrets.OPEN_GET_WEATHER }}'
          area='${{ secrets.AREA }}'
          step_range='${{ secrets.STEP_RANGE }}'
          if [ -z "$step_range" ]; then
            step_range='5000-10000:90,10001-12000:10'
          fi
          python3 main.py ${user} ${passwd} ${open_get_weather} ${area} ${step_range} daily
